// Auto-generated from Mindustry bundle_zh_CN.properties
// Content type → array of {name, cn} entries

export const VANILLA_CONTENT = {
    Planet: [
        {name: 'sun', cn: '太阳'},
        {name: 'serpulo', cn: '塞普罗'},
        {name: 'erekir', cn: '埃里克尔'},
        {name: 'tantros', cn: 'Tantros'},
    ],
    SectorPreset: [
        // Serpulo
        {name: 'groundZero', cn: '零号地区'},
        {name: 'crateredBattleground', cn: '陨坑战场'},
        {name: 'frozenForest', cn: '冰冻森林'},
        {name: 'biomassFacility', cn: '生物质合成区'},
        {name: 'taintedWoods', cn: '孢染丛林'},
        {name: 'ruinousShores', cn: '遗迹海岸'},
        {name: 'stainedMountains', cn: '绵延群山'},
        {name: 'tarFields', cn: '焦油田'},
        {name: 'desolateRift', cn: '荒芜裂谷'},
        {name: 'nuclearComplex', cn: '核裂阵'},
        {name: 'overgrowth', cn: '增生区'},
        {name: 'saltFlats', cn: '盐碱荒滩'},
        {name: 'fungalPass', cn: '真菌通道'},
        {name: 'windsweptIslands', cn: '风吹群岛'},
        {name: 'extractionOutpost', cn: '萃取前哨'},
        {name: 'facility32m', cn: '工业区 32M'},
        {name: 'infestedCanyons', cn: '菌疫峡谷'},
        {name: 'planetaryTerminal', cn: '行星发射终端'},
        {name: 'coastline', cn: '边际海湾'},
        {name: 'navalFortress', cn: '海军要塞'},
        {name: 'atolls', cn: '环礁群岛'},
        {name: 'testingGrounds', cn: '实验禁区'},
        {name: 'perilousHarbor', cn: '深险峡湾'},
        {name: 'weatheredChannels', cn: '风化海峡'},
        {name: 'frontier', cn: '边陲哨站'},
        {name: 'sunkenPier', cn: '沉没码头'},
        {name: 'mycelialBastion', cn: '菌丝堡垒'},
        {name: 'littoralShipyard', cn: '海滨船厂'},
        {name: 'impact0078', cn: '冲击区 0078'},
        // Erekir
        {name: 'onset', cn: '始发地区'},
        {name: 'aegis', cn: '庇护前哨'},
        {name: 'lake', cn: '岩浆湖'},
        {name: 'intersect', cn: '交错丘陵'},
        {name: 'atlas', cn: '风化山脉'},
        {name: 'split', cn: '横断山谷'},
        {name: 'basin', cn: '风蚀盆地'},
        {name: 'marsh', cn: '芳油湿地'},
        {name: 'peaks', cn: '横堑峰峦'},
        {name: 'ravine', cn: '贫瘠峡谷'},
        {name: 'caldera', cn: '破碎火山'},
        {name: 'stronghold', cn: '晶石要塞'},
        {name: 'crevice', cn: '碳岩裂隙'},
        {name: 'siege', cn: '平行岭谷'},
        {name: 'crossroads', cn: '十字路口'},
        {name: 'karst', cn: '岩溶洞穴'},
        {name: 'origin', cn: '起源'},
    ],
    Weather: [
        {name: 'rain', cn: '降雨'},
        {name: 'snowing', cn: '降雪'},
        {name: 'sandstorm', cn: '沙尘暴'},
        {name: 'sporestorm', cn: '孢子风暴'},
        {name: 'fog', cn: '雾'},
    ],
    Sound: [
        // Shoot sounds
        {name: 'shoot', cn: '射击'}, {name: 'shootAfflict', cn: '射击-劫难'},
        {name: 'shootArc', cn: '射击-电弧'}, {name: 'shootArtillery', cn: '射击-火炮'},
        {name: 'shootDuo', cn: '射击-双管'}, {name: 'shootFlame', cn: '射击-火焰'},
        {name: 'shootLaser', cn: '射击-激光'}, {name: 'shootMissile', cn: '射击-导弹'},
        {name: 'shootRipple', cn: '射击-浪涌'}, {name: 'shootSap', cn: '射击-汲取'},
        {name: 'shootScatter', cn: '射击-分裂'}, {name: 'shootSalvo', cn: '射击-齐射'},
        {name: 'shootSpectre', cn: '射击-幽灵'}, {name: 'shootCyclone', cn: '射击-气旋'},
        {name: 'shootFuse', cn: '射击-雷光'}, {name: 'shootMeltdown', cn: '射击-熔毁'},
        {name: 'shootSmite', cn: '射击-天谴'},
        // Explosion sounds
        {name: 'explosion', cn: '爆炸'}, {name: 'explosionReactor', cn: '爆炸-反应堆'},
        {name: 'explosionCore', cn: '爆炸-核心'}, {name: 'explosionTitan', cn: '爆炸-泰坦'},
        // Loop sounds
        {name: 'loopConveyor', cn: '循环-传送带'}, {name: 'loopDrill', cn: '循环-钻头'},
        {name: 'loopMachine', cn: '循环-机器'}, {name: 'loopHum', cn: '循环-嗡鸣'},
        {name: 'loopSteam', cn: '循环-蒸汽'}, {name: 'loopPulse', cn: '循环-脉冲'},
        {name: 'loopFire', cn: '循环-火焰'}, {name: 'loopShield', cn: '循环-护盾'},
        {name: 'loopBuild', cn: '循环-建造'}, {name: 'loopTech', cn: '循环-科技'},
        {name: 'loopSmelter', cn: '循环-冶炼'}, {name: 'loopCultivator', cn: '循环-培养'},
        {name: 'loopGrind', cn: '循环-研磨'}, {name: 'loopSpray', cn: '循环-喷洒'},
        {name: 'loopElectricHum', cn: '循环-电力'}, {name: 'loopCutter', cn: '循环-切割'},
        // Movement sounds
        {name: 'mechStep', cn: '机甲脚步'}, {name: 'tankMove', cn: '坦克移动'},
        {name: 'walkerStep', cn: '步行机脚步'}, {name: 'shipMove', cn: '飞船移动'},
        // Weather sounds
        {name: 'rain', cn: '雨声'}, {name: 'wind', cn: '风声'},
        // UI sounds
        {name: 'uiButton', cn: '按钮'}, {name: 'uiClick', cn: '点击'},
        {name: 'uiUnlock', cn: '解锁'},
        // Other sounds
        {name: 'blockBreak', cn: '方块破坏'}, {name: 'blockPlace', cn: '方块放置'},
        {name: 'click', cn: '点击'}, {name: 'door', cn: '门'},
        {name: 'unitCreate', cn: '单位创建'}, {name: 'unitExplode', cn: '单位爆炸'},
        {name: 'healWave', cn: '治疗波'}, {name: 'shieldWave', cn: '护盾波'},
        {name: 'coreLaunch', cn: '核心发射'}, {name: 'padLand', cn: '着陆'},
        {name: 'massdriver', cn: '质量驱动器'}, {name: 'shockwaveTower', cn: '震爆塔'},
        {name: 'drillCharge', cn: '钻头蓄力'}, {name: 'drillImpact', cn: '钻头冲击'},
        {name: 'wavesSpawn', cn: '波次生成'},
    ],
    BulletType: [
        {name: 'standardCopper', cn: '标准铜质'},
        {name: 'standardDense', cn: '标准致密'},
        {name: 'standardLead', cn: '标准铅质'},
        {name: 'standardThorium', cn: '标准钍质'},
        {name: 'standardHoming', cn: '标准追踪'},
        {name: 'standardIncendiary', cn: '标准燃烧'},
        {name: 'standardGlass', cn: '标准玻璃'},
        {name: 'standardTungsten', cn: '标准钨质'},
        {name: 'standardSilicon', cn: '标准硅'},
        {name: 'standardPlastic', cn: '标准塑料'},
        {name: 'standardSurge', cn: '标准浪涌'},
        {name: 'flakLead', cn: '防空弹-铅质'},
        {name: 'flakScrap', cn: '防空弹-废料'},
        {name: 'flakGlass', cn: '防空弹-玻璃'},
        {name: 'flakPlastic', cn: '防空弹-塑料'},
        {name: 'flakThorium', cn: '防空弹-钍质'},
        {name: 'flakTungsten', cn: '防空弹-钨质'},
        {name: 'missileExplosive', cn: '导弹-高爆'},
        {name: 'missileIncendiary', cn: '导弹-燃烧'},
        {name: 'missileSurge', cn: '导弹-浪涌'},
        {name: 'missileSalt', cn: '导弹-盐雾'},
        {name: 'missileSwarm', cn: '导弹-蜂群'},
        {name: 'missileJavelin', cn: '导弹-标枪'},
        {name: 'missileSawar', cn: '导弹-铣刀'},
        {name: 'missileRevenant', cn: '导弹-亡魂'},
        {name: 'missileMechSawar', cn: '导弹-机甲铣刀'},
        {name: 'missileEclipse', cn: '导弹-日蚀'},
        {name: 'missilePilum', cn: '导弹-重标枪'},
        {name: 'missileSabot', cn: '导弹-破甲'},
        {name: 'missileSoma', cn: '导弹-索玛'},
        {name: 'artilleryDense', cn: '榴弹-致密'},
        {name: 'artilleryExplosive', cn: '榴弹-高爆'},
        {name: 'artilleryPlastic', cn: '榴弹-塑料'},
        {name: 'artilleryHoming', cn: '榴弹-追踪'},
        {name: 'liquidShot', cn: '液体弹'},
        {name: 'cryoShot', cn: '冷冻液弹'},
        {name: 'incendiaryShot', cn: '燃烧弹'},
        {name: 'slimeShot', cn: '粘液弹'},
        {name: 'tarShot', cn: '焦油弹'},
        {name: 'oilShot', cn: '石油弹'},
        {name: 'waterShot', cn: '水弹'},
        {name: 'lightning', cn: '闪电'},
        {name: 'pointDefense', cn: '点防御'},
        {name: 'shieldCharge', cn: '护盾充能'},
        {name: 'healBullet', cn: '治疗弹'},
        {name: 'healBeam', cn: '治疗光束'},
        {name: 'healMist', cn: '治疗雾'},
        {name: 'plasmas', cn: '等离子'},
        {name: 'flameShot', cn: '火焰弹'},
        {name: 'meltdownLaser', cn: '熔毁激光'},
        {name: 'thoriumShard', cn: '钍碎片'},
        {name: 'sap', cn: '汲取'},
    ],
    Block: [
        {name: 'additive-reconstructor', cn: '数增级单位重构工厂'},
        {name: 'advanced-launch-pad', cn: '发射台'},
        {name: 'afflict', cn: '劫难'},
        {name: 'air-factory', cn: '空军工厂'},
        {name: 'arc', cn: '电弧'},
        {name: 'arkycite-floor', cn: '芳油'},
        {name: 'arkyic-boulder', cn: '芳石块'},
        {name: 'arkyic-stone', cn: '芳石'},
        {name: 'arkyic-vent', cn: '芳石喷口'},
        {name: 'arkyic-wall', cn: '芳石墙'},
        {name: 'armored-conveyor', cn: '装甲传送带'},
        {name: 'armored-duct', cn: '装甲管道'},
        {name: 'atmospheric-concentrator', cn: '大气收集器'},
        {name: 'basalt', cn: '玄武岩'},
        {name: 'basalt-boulder', cn: '玄武岩石块'},
        {name: 'basalt-vent', cn: '玄武岩喷口'},
        {name: 'basic-assembler-module', cn: '基本装配厂模块'},
        {name: 'battery', cn: '电池'},
        {name: 'battery-large', cn: '大型电池'},
        {name: 'beam-link', cn: '激光连接器'},
        {name: 'beam-node', cn: '激光节点'},
        {name: 'beam-tower', cn: '激光塔'},
        {name: 'beryllic-boulder', cn: '铍石块'},
        {name: 'beryllic-stone', cn: '铍石'},
        {name: 'beryllic-stone-wall', cn: '铍石墙'},
        {name: 'beryllium-wall', cn: '铍墙'},
        {name: 'beryllium-wall-large', cn: '大型铍墙'},
        {name: 'blast-door', cn: '防爆闸门'},
        {name: 'blast-drill', cn: '爆破钻头'},
        {name: 'blast-mixer', cn: '爆炸物混合器'},
        {name: 'bluemat', cn: '蓝地垫'},
        {name: 'boulder', cn: '石块'},
        {name: 'breach', cn: '撕裂'},
        {name: 'bridge-conduit', cn: '导管桥'},
        {name: 'bridge-conveyor', cn: '传送带桥'},
        {name: 'build-tower', cn: '建造塔'},
        {name: 'canvas', cn: '画板'},
        {name: 'carbide-crucible', cn: '碳化物坩埚'},
        {name: 'carbide-wall', cn: '碳化物墙'},
        {name: 'carbide-wall-large', cn: '大型碳化物墙'},
        {name: 'carbon-boulder', cn: '碳石块'},
        {name: 'carbon-stone', cn: '碳石'},
        {name: 'carbon-vent', cn: '碳石喷口'},
        {name: 'carbon-wall', cn: '碳石墙'},
        {name: 'char', cn: '焦土'},
        {name: 'character-overlay', cn: '标识贴片'},
        {name: 'character-overlay-white', cn: '标识贴片 (白色)'},
        {name: 'chemical-combustion-chamber', cn: '化学燃烧室'},
        {name: 'cliff', cn: '悬崖'},
        {name: 'cliff-crusher', cn: '墙壁粉碎机'},
        {name: 'coal-centrifuge', cn: '煤炭离心机'},
        {name: 'colored-floor', cn: '染色地板'},
        {name: 'colored-wall', cn: '染色墙壁'},
        {name: 'combustion-generator', cn: '火力发电机'},
        {name: 'conduit', cn: '导管'},
        {name: 'constructor', cn: '构筑器'},
        {name: 'container', cn: '容器'},
        {name: 'conveyor', cn: '传送带'},
        {name: 'copper-wall', cn: '铜墙'},
        {name: 'copper-wall-large', cn: '大型铜墙'},
        {name: 'core-acropolis', cn: '卫城核心'},
        {name: 'core-bastion', cn: '城堡核心'},
        {name: 'core-citadel', cn: '堡垒核心'},
        {name: 'core-foundation', cn: '次代核心'},
        {name: 'core-nucleus', cn: '终代核心'},
        {name: 'core-shard', cn: '初代核心'},
        {name: 'core-zone', cn: '核心区'},
        {name: 'crater-stone', cn: '陨石坑'},
        {name: 'cryofluid-mixer', cn: '冷冻液混合器'},
        {name: 'crystal-blocks', cn: '风化晶体'},
        {name: 'crystal-cluster', cn: '水晶簇'},
        {name: 'crystal-floor', cn: '晶石地板'},
        {name: 'crystalline-boulder', cn: '晶石块'},
        {name: 'crystalline-stone', cn: '晶石'},
        {name: 'crystalline-stone-wall', cn: '晶石墙'},
        {name: 'crystalline-vent', cn: '晶石喷口'},
        {name: 'crystal-orbs', cn: '晶石球'},
        {name: 'cultivator', cn: '培养机'},
        {name: 'cyanogen-synthesizer', cn: '氰合成机'},
        {name: 'cyclone', cn: '气旋'},
        {name: 'dacite', cn: '安山岩'},
        {name: 'dacite-boulder', cn: '安山石块'},
        {name: 'dacite-wall', cn: '安山岩墙'},
        {name: 'dark-metal', cn: '暗金属'},
        {name: 'dark-panel-1', cn: '暗面板 1'},
        {name: 'dark-panel-2', cn: '暗面板 2'},
        {name: 'dark-panel-3', cn: '暗面板 3'},
        {name: 'dark-panel-4', cn: '暗面板 4'},
        {name: 'dark-panel-5', cn: '暗面板 5'},
        {name: 'dark-panel-6', cn: '暗面板 6'},
        {name: 'darksand', cn: '黑沙'},
        {name: 'darksand-tainted-water', cn: '黑沙污水'},
        {name: 'darksand-water', cn: '黑沙浅滩'},
        {name: 'deconstructor', cn: '大型解构器'},
        {name: 'deep-tainted-water', cn: '深污水'},
        {name: 'deep-water', cn: '深水'},
        {name: 'dense-red-stone', cn: '高密红石'},
        {name: 'differential-generator', cn: '温差发电机'},
        {name: 'diffuse', cn: '扩散'},
        {name: 'diode', cn: '二极管'},
        {name: 'dirt', cn: '泥土'},
        {name: 'dirt-wall', cn: '泥土墙'},
        {name: 'disassembler', cn: '解离机'},
        {name: 'disperse', cn: '驱离'},
        {name: 'distributor', cn: '分配器'},
        {name: 'door', cn: '门'},
        {name: 'door-large', cn: '大门'},
        {name: 'duct', cn: '物品管道'},
        {name: 'duct-bridge', cn: '物品管道桥'},
        {name: 'duct-router', cn: '物品管道路由器'},
        {name: 'duct-unloader', cn: '管道装卸器'},
        {name: 'dune-wall', cn: '沙丘岩'},
        {name: 'duo', cn: '双管'},
        {name: 'electric-heater', cn: '电制热机'},
        {name: 'electrolyzer', cn: '电解机'},
        {name: 'empty', cn: '空'},
        {name: 'eruption-drill', cn: '爆裂钻头'},
        {name: 'exponential-reconstructor', cn: '多幂级单位重构工厂'},
        {name: 'ferric-boulder', cn: '铁石块'},
        {name: 'ferric-craters', cn: '铁陨石坑'},
        {name: 'ferric-stone', cn: '铁石'},
        {name: 'ferric-stone-wall', cn: '铁石墙'},
        {name: 'flux-reactor', cn: '通量反应堆'},
        {name: 'force-projector', cn: '力墙投影'},
        {name: 'foreshadow', cn: '厄兆'},
        {name: 'fuse', cn: '雷光'},
        {name: 'graphite-press', cn: '石墨压缩机'},
        {name: 'graphitic-wall', cn: '石墨墙'},
        {name: 'grass', cn: '草地'},
        {name: 'ground-factory', cn: '陆军工厂'},
        {name: 'hail', cn: '冰雹'},
        {name: 'heat-reactor', cn: '热量反应堆'},
        {name: 'heat-redirector', cn: '热量传输机'},
        {name: 'heat-router', cn: '热量路由器'},
        {name: 'heat-source', cn: '热量源'},
        {name: 'hotrock', cn: '灼热岩石'},
        {name: 'hyper-processor', cn: '超核处理器'},
        {name: 'ice', cn: '冰'},
        {name: 'ice-snow', cn: '冰雪地'},
        {name: 'ice-wall', cn: '冰墙'},
        {name: 'illuminator', cn: '照明器'},
        {name: 'impact-drill', cn: '冲击钻头'},
        {name: 'impact-reactor', cn: '冲击反应堆'},
        {name: 'impulse-pump', cn: '脉冲泵'},
        {name: 'incinerator', cn: '焚化炉'},
        {name: 'interplanetary-accelerator', cn: '行星际加速器'},
        {name: 'inverted-sorter', cn: '反向分类器'},
        {name: 'item-source', cn: '物品源'},
        {name: 'item-void', cn: '物品黑洞'},
        {name: 'junction', cn: '交叉器'},
        {name: 'kiln', cn: '窑炉'},
        {name: 'lancer', cn: '蓝瑟'},
        {name: 'landing-pad', cn: '接收台'},
        {name: 'large-canvas', cn: '大型画板'},
        {name: 'large-cliff-crusher', cn: '高级墙壁粉碎机'},
        {name: 'large-constructor', cn: '大型构筑器'},
        {name: 'large-logic-display', cn: '大型逻辑显示屏'},
        {name: 'large-payload-mass-driver', cn: '大型载荷质量驱动器'},
        {name: 'large-plasma-bore', cn: '高级等离子钻机'},
        {name: 'large-shield-projector', cn: '大型护盾投影器'},
        {name: 'laser-drill', cn: '激光钻头'},
        {name: 'launch-pad', cn: '发射台[lightgray]（旧版）'},
        {name: 'liquid-container', cn: '流体容器'},
        {name: 'liquid-junction', cn: '流体交叉器'},
        {name: 'liquid-router', cn: '流体路由器'},
        {name: 'liquid-source', cn: '液体源'},
        {name: 'liquid-tank', cn: '流体储罐'},
        {name: 'liquid-void', cn: '液体黑洞'},
        {name: 'logic-display', cn: '逻辑显示屏'},
        {name: 'logic-processor', cn: '逻辑处理器'},
        {name: 'lustre', cn: '光辉'},
        {name: 'magmarock', cn: '熔融岩石'},
        {name: 'malign', cn: '魔灵'},
        {name: 'mass-driver', cn: '质量驱动器'},
        {name: 'mechanical-drill', cn: '机械钻头'},
        {name: 'mechanical-pump', cn: '机械泵'},
        {name: 'mech-assembler', cn: '机甲组装厂'},
        {name: 'mech-fabricator', cn: '机甲制造厂'},
        {name: 'mech-refabricator', cn: '机甲重构厂'},
        {name: 'meltdown', cn: '熔毁'},
        {name: 'melter', cn: '熔炉'},
        {name: 'memory-bank', cn: '内存库'},
        {name: 'memory-cell', cn: '内存元'},
        {name: 'mender', cn: '修理器'},
        {name: 'mend-projector', cn: '修理投影'},
        {name: 'message', cn: '信息板'},
        {name: 'metal-floor-2', cn: '金属地板 2'},
        {name: 'metal-floor-3', cn: '金属地板 3'},
        {name: 'metal-floor-4', cn: '金属地板 4'},
        {name: 'metal-floor-5', cn: '金属地板 5'},
        {name: 'metal-floor', cn: '金属地板 1'},
        {name: 'metal-floor-damaged', cn: '损坏的金属地板'},
        {name: 'metal-tiles-10', cn: '金属地基 10'},
        {name: 'metal-tiles-11', cn: '金属地基 11'},
        {name: 'metal-tiles-12', cn: '金属地基 12'},
        {name: 'metal-tiles-13', cn: '金属地基 13'},
        {name: 'metal-tiles-1', cn: '金属地基 1'},
        {name: 'metal-tiles-2', cn: '金属地基 2'},
        {name: 'metal-tiles-3', cn: '金属地基 3'},
        {name: 'metal-tiles-4', cn: '金属地基 4'},
        {name: 'metal-tiles-5', cn: '金属地基 5'},
        {name: 'metal-tiles-6', cn: '金属地基 6'},
        {name: 'metal-tiles-7', cn: '金属地基 7'},
        {name: 'metal-tiles-8', cn: '金属地基 8'},
        {name: 'metal-tiles-9', cn: '金属地基 9'},
        {name: 'metal-wall-1', cn: '金属墙 1'},
        {name: 'metal-wall-2', cn: '金属墙 2'},
        {name: 'metal-wall-3', cn: '金属墙 3'},
        {name: 'micro-processor', cn: '微型处理器'},
        {name: 'molten-slag', cn: '矿渣液'},
        {name: 'moss', cn: '苔藓地'},
        {name: 'mud', cn: '泥巴'},
        {name: 'multiplicative-reconstructor', cn: '倍乘级单位重构工厂'},
        {name: 'multi-press', cn: '多重压缩机'},
        {name: 'naval-factory', cn: '海军工厂'},
        {name: 'neoplasia-reactor', cn: '瘤变反应堆'},
        {name: 'oil-extractor', cn: '石油钻井'},
        {name: 'overdrive-dome', cn: '超速穹顶'},
        {name: 'overdrive-projector', cn: '超速投影'},
        {name: 'overflow-duct', cn: '溢流管道'},
        {name: 'overflow-gate', cn: '溢流门'},
        {name: 'oxidation-chamber', cn: '氧化室'},
        {name: 'parallax', cn: '差扰'},
        {name: 'payload-conveyor', cn: '载荷传送带'},
        {name: 'payload-loader', cn: '载荷装载器'},
        {name: 'payload-mass-driver', cn: '载荷质量驱动器'},
        {name: 'payload-router', cn: '载荷路由器'},
        {name: 'payload-source', cn: '载荷源'},
        {name: 'payload-unloader', cn: '载荷卸载器'},
        {name: 'payload-void', cn: '载荷黑洞'},
        {name: 'pebbles', cn: '鹅卵石'},
        {name: 'phase-conduit', cn: '相织布导管桥'},
        {name: 'phase-conveyor', cn: '相织布传送带桥'},
        {name: 'phase-heater', cn: '相织制热机'},
        {name: 'phase-synthesizer', cn: '相织布合成机'},
        {name: 'phase-wall', cn: '相织布墙'},
        {name: 'phase-wall-large', cn: '大型相织布墙'},
        {name: 'phase-weaver', cn: '相织布编织器'},
        {name: 'pine', cn: '松树'},
        {name: 'plasma-bore', cn: '等离子钻机'},
        {name: 'plastanium-compressor', cn: '塑钢压缩机'},
        {name: 'plastanium-conveyor', cn: '塑钢传送带'},
        {name: 'plastanium-wall', cn: '塑钢墙'},
        {name: 'plastanium-wall-large', cn: '大型塑钢墙'},
        {name: 'plated-conduit', cn: '电镀导管'},
        {name: 'pneumatic-drill', cn: '气动钻头'},
        {name: 'pooled-cryofluid', cn: '冷冻液'},
        {name: 'power-node', cn: '电力节点'},
        {name: 'power-node-large', cn: '大型电力节点'},
        {name: 'power-source', cn: '电力源'},
        {name: 'power-void', cn: '电力黑洞'},
        {name: 'prime-refabricator', cn: '高级再重构工厂'},
        {name: 'pulse-conduit', cn: '脉冲导管'},
        {name: 'pulverizer', cn: '粉碎机'},
        {name: 'pur-bush', cn: '紫灌木丛'},
        {name: 'pyratite-mixer', cn: '硫化物混合器'},
        {name: 'pyrolysis-generator', cn: '热解发生器'},
        {name: 'radar', cn: '雷达'},
        {name: 'red-diamond-wall', cn: '红钻墙'},
        {name: 'red-ice', cn: '红冰'},
        {name: 'red-ice-boulder', cn: '红冰石块'},
        {name: 'red-ice-wall', cn: '红冰墙'},
        {name: 'redmat', cn: '红地垫'},
        {name: 'red-stone', cn: '红石'},
        {name: 'red-stone-boulder', cn: '红石块'},
        {name: 'red-stone-vent', cn: '红石喷口'},
        {name: 'red-stone-wall', cn: '红石墙'},
        {name: 'redweed', cn: '赤藻'},
        {name: 'regen-projector', cn: '再生投影器'},
        {name: 'regolith', cn: '风化岩'},
        {name: 'regolith-wall', cn: '风化墙'},
        {name: 'reinforced-bridge-conduit', cn: '强化流体带桥'},
        {name: 'reinforced-conduit', cn: '强化导管'},
        {name: 'reinforced-container', cn: '强化容器'},
        {name: 'reinforced-liquid-container', cn: '强化流体容器'},
        {name: 'reinforced-liquid-junction', cn: '强化流体交叉器'},
        {name: 'reinforced-liquid-router', cn: '强化流体路由器'},
        {name: 'reinforced-liquid-tank', cn: '强化流体储罐'},
        {name: 'reinforced-message', cn: '强化信息板'},
        {name: 'reinforced-payload-conveyor', cn: '强化载荷传送带'},
        {name: 'reinforced-payload-router', cn: '强化载荷路由器'},
        {name: 'reinforced-pump', cn: '强化泵'},
        {name: 'reinforced-surge-wall', cn: '强化合金墙'},
        {name: 'reinforced-surge-wall-large', cn: '大型强化合金墙'},
        {name: 'reinforced-vault', cn: '强化仓库'},
        {name: 'remove-ore', cn: '移除矿'},
        {name: 'remove-wall', cn: '移除墙体'},
        {name: 'repair-point', cn: '维修点'},
        {name: 'repair-turret', cn: '维修塔'},
        {name: 'rhyolite', cn: '流纹岩'},
        {name: 'rhyolite-boulder', cn: '流纹石块'},
        {name: 'rhyolite-crater', cn: '流纹岩坑'},
        {name: 'rhyolite-vent', cn: '流纹石喷口'},
        {name: 'rhyolite-wall', cn: '流纹岩墙'},
        {name: 'ripple', cn: '浪涌'},
        {name: 'rotary-pump', cn: '回转泵'},
        {name: 'rough-rhyolite', cn: '粗糙流纹岩'},
        {name: 'router', cn: '路由器'},
        {name: 'rtg-generator', cn: 'RTG 发电机'},
        {name: 'rune-overlay', cn: '符文贴片'},
        {name: 'rune-overlay-crux', cn: '符文贴片 （红队）'},
        {name: 'salt', cn: '盐碱地'},
        {name: 'salt-wall', cn: '盐墙'},
        {name: 'salvo', cn: '齐射'},
        {name: 'sand-boulder', cn: '砂岩'},
        {name: 'sand-floor', cn: '沙子'},
        {name: 'sand-wall', cn: '沙墙'},
        {name: 'sand-water', cn: '浅滩'},
        {name: 'scathe', cn: '创伤'},
        {name: 'scatter', cn: '分裂'},
        {name: 'scorch', cn: '火焰'},
        {name: 'scrap-wall', cn: '废墙'},
        {name: 'scrap-wall-gigantic', cn: '超巨型废墙'},
        {name: 'scrap-wall-huge', cn: '巨型废墙'},
        {name: 'scrap-wall-large', cn: '大型废墙'},
        {name: 'segment', cn: '裂解'},
        {name: 'separator', cn: '分离机'},
        {name: 'shale', cn: '页岩地'},
        {name: 'shale-boulder', cn: '页岩石块'},
        {name: 'shale-wall', cn: '页岩墙'},
        {name: 'shallow-water', cn: '水'},
        {name: 'shielded-wall', cn: '盾墙'},
        {name: 'shield-projector', cn: '护盾投影器'},
        {name: 'ship-assembler', cn: '飞船组装厂'},
        {name: 'ship-fabricator', cn: '飞船制造厂'},
        {name: 'ship-refabricator', cn: '飞船重构厂'},
        {name: 'shock-mine', cn: '脉冲地雷'},
        {name: 'shockwave-tower', cn: '震爆塔'},
        {name: 'shrubs', cn: '灌木丛'},
        {name: 'silicon-arc-furnace', cn: '电弧硅炉'},
        {name: 'silicon-crucible', cn: '热能坩埚'},
        {name: 'silicon-smelter', cn: '硅冶炼厂'},
        {name: 'slag-centrifuge', cn: '矿渣离心机'},
        {name: 'slag-heater', cn: '矿渣制热机'},
        {name: 'slag-incinerator', cn: '矿渣焚化炉'},
        {name: 'small-deconstructor', cn: '解构器'},
        {name: 'small-heat-redirector', cn: '小型热量传输机'},
        {name: 'smite', cn: '天谴'},
        {name: 'snow', cn: '雪'},
        {name: 'snow-boulder', cn: '雪石块'},
        {name: 'snow-pine', cn: '雪树'},
        {name: 'snow-wall', cn: '雪墙'},
        {name: 'solar-panel', cn: '太阳能板'},
        {name: 'solar-panel-large', cn: '大型太阳能板'},
        {name: 'sorter', cn: '分类器'},
        {name: 'space', cn: '太空'},
        {name: 'spawn', cn: '敌人出生点'},
        {name: 'spectre', cn: '幽灵'},
        {name: 'spore-cluster', cn: '孢子簇'},
        {name: 'spore-moss', cn: '孢子苔藓地'},
        {name: 'spore-pine', cn: '孢子树'},
        {name: 'spore-press', cn: '孢子压缩机'},
        {name: 'spore-wall', cn: '孢子墙'},
        {name: 'steam-generator', cn: '涡轮发电机'},
        {name: 'stone', cn: '石头'},
        {name: 'stone-vent', cn: '岩石喷口'},
        {name: 'stone-wall', cn: '石墙'},
        {name: 'sublimate', cn: '升华'},
        {name: 'surge-conveyor', cn: '合金传送带'},
        {name: 'surge-crucible', cn: '合金坩埚'},
        {name: 'surge-router', cn: '合金路由器'},
        {name: 'surge-smelter', cn: '合金冶炼厂'},
        {name: 'surge-tower', cn: '巨浪电力塔'},
        {name: 'surge-wall', cn: '合金墙'},
        {name: 'surge-wall-large', cn: '大型合金墙'},
        {name: 'swarmer', cn: '蜂群'},
        {name: 'switch', cn: '开关'},
        {name: 'tainted-water', cn: '污水'},
        {name: 'tank-assembler', cn: '坦克组装厂'},
        {name: 'tank-fabricator', cn: '坦克制造厂'},
        {name: 'tank-refabricator', cn: '坦克重构厂'},
        {name: 'tar', cn: '石油'},
        {name: 'tendrils', cn: '卷须'},
        {name: 'tetrative-reconstructor', cn: '无量级单位重构工厂'},
        {name: 'thermal-generator', cn: '热能发电机'},
        {name: 'thorium-reactor', cn: '钍反应堆'},
        {name: 'thorium-wall', cn: '钍墙'},
        {name: 'thorium-wall-large', cn: '大型钍墙'},
        {name: 'thruster', cn: '推进器残骸'},
        {name: 'tile-logic-display', cn: '逻辑显示单元'},
        {name: 'titan', cn: '泰坦'},
        {name: 'titanium-conveyor', cn: '钛传送带'},
        {name: 'titanium-wall', cn: '钛墙'},
        {name: 'titanium-wall-large', cn: '大型钛墙'},
        {name: 'tsunami', cn: '海啸'},
        {name: 'tungsten-wall', cn: '钨墙'},
        {name: 'tungsten-wall-large', cn: '大型钨墙'},
        {name: 'turbine-condenser', cn: '涡轮冷凝器'},
        {name: 'underflow-duct', cn: '反向溢流管'},
        {name: 'underflow-gate', cn: '反向溢流门'},
        {name: 'unit-cargo-loader', cn: '单位物流装载器'},
        {name: 'unit-cargo-unload-point', cn: '单位物流卸载点'},
        {name: 'unit-repair-tower', cn: '单位维修塔'},
        {name: 'unloader', cn: '装卸器'},
        {name: 'vault', cn: '仓库'},
        {name: 'vent-condenser', cn: '排气冷凝器'},
        {name: 'vibrant-crystal-cluster', cn: '鲜艳水晶簇'},
        {name: 'water-extractor', cn: '抽水机'},
        {name: 'wave', cn: '波浪'},
        {name: 'white-tree', cn: '白树'},
        {name: 'white-tree-dead', cn: '枯萎的白树'},
        {name: 'world-cell', cn: '世界内存元'},
        {name: 'world-message', cn: '世界信息板'},
        {name: 'world-processor', cn: '世界处理器'},
        {name: 'world-switch', cn: '世界开关'},
        {name: 'yellowcoral', cn: '黄珊瑚'},
        {name: 'yellow-stone', cn: '黄石'},
        {name: 'yellow-stone-boulder', cn: '黄石块'},
        {name: 'yellow-stone-plates', cn: '黄石地板'},
        {name: 'yellow-stone-vent', cn: '黄石喷口'},
        {name: 'yellow-stone-wall', cn: '黄石墙'}
    ],
    Item: [
        {name: 'beryllium', cn: '铍'},
        {name: 'blast-compound', cn: '爆炸混合物'},
        {name: 'carbide', cn: '碳化物'},
        {name: 'coal', cn: '煤炭'},
        {name: 'copper', cn: '铜'},
        {name: 'dormant-cyst', cn: '休眠囊肿'},
        {name: 'fissile-matter', cn: '裂变产物'},
        {name: 'graphite', cn: '石墨'},
        {name: 'lead', cn: '铅'},
        {name: 'metaglass', cn: '钢化玻璃'},
        {name: 'oxide', cn: '氧化物'},
        {name: 'phase-fabric', cn: '相织布'},
        {name: 'plastanium', cn: '塑钢'},
        {name: 'pyratite', cn: '硫化物'},
        {name: 'sand', cn: '沙'},
        {name: 'scrap', cn: '废料'},
        {name: 'silicon', cn: '硅'},
        {name: 'spore-pod', cn: '孢子荚'},
        {name: 'surge-alloy', cn: '巨浪合金'},
        {name: 'thorium', cn: '钍'},
        {name: 'titanium', cn: '钛'},
        {name: 'tungsten', cn: '钨'}
    ],
    Liquid: [
        {name: 'arkycite', cn: '芳油'},
        {name: 'cryofluid', cn: '冷冻液'},
        {name: 'cyanogen', cn: '氰气'},
        {name: 'gallium', cn: '镓液'},
        {name: 'hydrogen', cn: '氢气'},
        {name: 'neoplasm', cn: '瘤液'},
        {name: 'nitrogen', cn: '氮气'},
        {name: 'oil', cn: '石油'},
        {name: 'ozone', cn: '臭氧'},
        {name: 'slag', cn: '矿渣'},
        {name: 'water', cn: '水'}
    ],
    UnitType: [
        {name: 'aegires', cn: '玄武'},
        {name: 'alpha', cn: '阿尔法'},
        {name: 'anthicus', cn: '天灾'},
        {name: 'antumbra', cn: '月影'},
        {name: 'arkyid', cn: '毒蛊'},
        {name: 'assembly-drone', cn: '装配无人机'},
        {name: 'atrax', cn: '毒蛛'},
        {name: 'avert', cn: '遮蔽'},
        {name: 'beta', cn: '贝塔'},
        {name: 'bryde', cn: '戟鲸'},
        {name: 'cleroi', cn: '天赐'},
        {name: 'collaris', cn: '天帝'},
        {name: 'conquer', cn: '领主'},
        {name: 'corvus', cn: '死星'},
        {name: 'crawler', cn: '爬虫'},
        {name: 'cyerce', cn: '江豚'},
        {name: 'dagger', cn: '尖刀'},
        {name: 'disrupt', cn: '悲怆'},
        {name: 'eclipse', cn: '日蚀'},
        {name: 'elude', cn: '挣脱'},
        {name: 'emanate', cn: '发散'},
        {name: 'evoke', cn: '苏醒'},
        {name: 'flare', cn: '星辉'},
        {name: 'fortress', cn: '堡垒'},
        {name: 'gamma', cn: '伽马'},
        {name: 'horizon', cn: '天垠'},
        {name: 'incite', cn: '策动'},
        {name: 'latum', cn: 'Latum'},
        {name: 'locus', cn: '循迹'},
        {name: 'mace', cn: '战锤'},
        {name: 'manifold', cn: '货运无人机'},
        {name: 'mega', cn: '巨像'},
        {name: 'merui', cn: '天守'},
        {name: 'minke', cn: '飞鲨'},
        {name: 'mono', cn: '独影'},
        {name: 'navanax', cn: '龙王'},
        {name: 'nova', cn: '新星'},
        {name: 'obviate', cn: '消散'},
        {name: 'oct', cn: '要塞'},
        {name: 'omura', cn: '海神'},
        {name: 'oxynoe', cn: '电鳗'},
        {name: 'poly', cn: '幻型'},
        {name: 'precept', cn: '准绳'},
        {name: 'pulsar', cn: '恒星'},
        {name: 'quad', cn: '雷霆'},
        {name: 'quasar', cn: '耀星'},
        {name: 'quell', cn: '遏止'},
        {name: 'reign', cn: '王座'},
        {name: 'renale', cn: 'Renale'},
        {name: 'retusa', cn: '潜螺'},
        {name: 'risso', cn: '梭鱼'},
        {name: 'scepter', cn: '权杖'},
        {name: 'sei', cn: '蛟龙'},
        {name: 'spiroct', cn: '血蛭'},
        {name: 'stell', cn: '围护'},
        {name: 'tecta', cn: '天理'},
        {name: 'toxopid', cn: '天蝎'},
        {name: 'vanquish', cn: '征服'},
        {name: 'vela', cn: '灾星'},
        {name: 'zenith', cn: '苍穹'}
    ],
    StatusEffect: [
        {name: 'none', cn: 'none'},
        {name: 'burning', cn: '燃烧'},
        {name: 'freezing', cn: '冻结'},
        {name: 'wet', cn: '潮湿'},
        {name: 'muddy', cn: '泥泞'},
        {name: 'melting', cn: '熔化'},
        {name: 'sapped', cn: '弱化'},
        {name: 'electrified', cn: '麻痹'},
        {name: 'spore-slowed', cn: '孢子减速'},
        {name: 'tarred', cn: '油浸'},
        {name: 'overdrive', cn: '过载'},
        {name: 'overclock', cn: '超频'},
        {name: 'shocked', cn: '电击'},
        {name: 'blasted', cn: '爆炸'},
        {name: 'corroded', cn: '腐蚀'},
        {name: 'unmoving', cn: '静止'},
        {name: 'boss', cn: 'Boss'},
        {name: 'slow', cn: '缓慢'},
        {name: 'fast', cn: '迅捷'},
        {name: 'shielded', cn: '保护'},
        {name: 'disarmed', cn: '缴械'},
        {name: 'invincible', cn: 'invincible'},
        {name: 'dynamic', cn: 'dynamic'},
    ],
    Effect: [
        {name: 'none', cn: 'none'},
        {name: 'blockCrash', cn: 'blockCrash'},
        {name: 'trailFade', cn: 'trailFade'},
        {name: 'unitSpawn', cn: 'unitSpawn'},
        {name: 'unitCapKill', cn: 'unitCapKill'},
        {name: 'unitEnvKill', cn: 'unitEnvKill'},
        {name: 'unitControl', cn: 'unitControl'},
        {name: 'unitDespawn', cn: 'unitDespawn'},
        {name: 'unitSpirit', cn: 'unitSpirit'},
        {name: 'itemTransfer', cn: 'itemTransfer'},
        {name: 'pointBeam', cn: 'pointBeam'},
        {name: 'pointHit', cn: 'pointHit'},
        {name: 'hitScepterSecondary', cn: 'hitScepterSecondary'},
        {name: 'lightning', cn: 'lightning'},
        {name: 'coreBuildShockwave', cn: 'coreBuildShockwave'},
        {name: 'coreBuildBlock', cn: 'coreBuildBlock'},
        {name: 'pointShockwave', cn: 'pointShockwave'},
        {name: 'moveCommand', cn: 'moveCommand'},
        {name: 'attackCommand', cn: 'attackCommand'},
        {name: 'commandSend', cn: 'commandSend'},
        {name: 'upgradeCore', cn: 'upgradeCore'},
        {name: 'upgradeCoreBloom', cn: 'upgradeCoreBloom'},
        {name: 'placeBlock', cn: 'placeBlock'},
        {name: 'coreLaunchConstruct', cn: 'coreLaunchConstruct'},
        {name: 'tapBlock', cn: 'tapBlock'},
        {name: 'breakBlock', cn: 'breakBlock'},
        {name: 'payloadDeposit', cn: 'payloadDeposit'},
        {name: 'select', cn: 'select'},
        {name: 'smoke', cn: 'smoke'},
        {name: 'fallSmoke', cn: 'fallSmoke'},
        {name: 'unitWreck', cn: 'unitWreck'},
        {name: 'rocketSmoke', cn: 'rocketSmoke'},
        {name: 'rocketSmokeLarge', cn: 'rocketSmokeLarge'},
        {name: 'magmasmoke', cn: 'magmasmoke'},
        {name: 'spawn', cn: 'spawn'},
        {name: 'unitAssemble', cn: 'unitAssemble'},
        {name: 'padlaunch', cn: 'padlaunch'},
        {name: 'breakProp', cn: 'breakProp'},
        {name: 'unitDrop', cn: 'unitDrop'},
        {name: 'unitLand', cn: 'unitLand'},
        {name: 'unitDust', cn: 'unitDust'},
        {name: 'unitLandSmall', cn: 'unitLandSmall'},
        {name: 'unitPickup', cn: 'unitPickup'},
        {name: 'crawlDust', cn: 'crawlDust'},
        {name: 'landShock', cn: 'landShock'},
        {name: 'pickup', cn: 'pickup'},
        {name: 'sparkExplosion', cn: 'sparkExplosion'},
        {name: 'titanExplosion', cn: 'titanExplosion'},
        {name: 'titanExplosionLarge', cn: 'titanExplosionLarge'},
        {name: 'titanExplosionSmall', cn: 'titanExplosionSmall'},
        {name: 'titanExplosionFrag', cn: 'titanExplosionFrag'},
        {name: 'titanSmoke', cn: 'titanSmoke'},
        {name: 'titanSmokeLarge', cn: 'titanSmokeLarge'},
        {name: 'titanSmokeSmall', cn: 'titanSmokeSmall'},
        {name: 'coreExplosion', cn: 'coreExplosion'},
        {name: 'smokeAoeCloud', cn: 'smokeAoeCloud'},
        {name: 'missileTrailSmoke', cn: 'missileTrailSmoke'},
        {name: 'missileTrailSmokeSmall', cn: 'missileTrailSmokeSmall'},
        {name: 'neoplasmSplat', cn: 'neoplasmSplat'},
        {name: 'scatheExplosion', cn: 'scatheExplosion'},
        {name: 'scatheExplosionSmall', cn: 'scatheExplosionSmall'},
        {name: 'scatheLight', cn: 'scatheLight'},
        {name: 'scatheLightSmall', cn: 'scatheLightSmall'},
        {name: 'titanLightSmall', cn: 'titanLightSmall'},
        {name: 'scatheSlash', cn: 'scatheSlash'},
        {name: 'dynamicSpikes', cn: 'dynamicSpikes'},
        {name: 'greenBomb', cn: 'greenBomb'},
        {name: 'greenLaserCharge', cn: 'greenLaserCharge'},
        {name: 'greenLaserChargeSmall', cn: 'greenLaserChargeSmall'},
        {name: 'greenCloud', cn: 'greenCloud'},
        {name: 'healWaveDynamic', cn: 'healWaveDynamic'},
        {name: 'healWave', cn: 'healWave'},
        {name: 'heal', cn: 'heal'},
        {name: 'dynamicWave', cn: 'dynamicWave'},
        {name: 'shieldWave', cn: 'shieldWave'},
        {name: 'shieldApply', cn: 'shieldApply'},
        {name: 'disperseTrail', cn: 'disperseTrail'},
        {name: 'hitBulletSmall', cn: 'hitBulletSmall'},
        {name: 'hitBulletColor', cn: 'hitBulletColor'},
        {name: 'hitSquaresColor', cn: 'hitSquaresColor'},
        {name: 'hitFuse', cn: 'hitFuse'},
        {name: 'hitBulletBig', cn: 'hitBulletBig'},
        {name: 'hitFlameSmall', cn: 'hitFlameSmall'},
        {name: 'hitFlamePlasma', cn: 'hitFlamePlasma'},
        {name: 'hitLiquid', cn: 'hitLiquid'},
        {name: 'hitLaserBlast', cn: 'hitLaserBlast'},
        {name: 'hitEmpSpark', cn: 'hitEmpSpark'},
        {name: 'hitLancer', cn: 'hitLancer'},
        {name: 'hitLancerLow', cn: 'hitLancerLow'},
        {name: 'hitBeam', cn: 'hitBeam'},
        {name: 'hitFlameBeam', cn: 'hitFlameBeam'},
        {name: 'hitMeltdown', cn: 'hitMeltdown'},
        {name: 'hitMeltHeal', cn: 'hitMeltHeal'},
        {name: 'instBomb', cn: 'instBomb'},
        {name: 'instTrail', cn: 'instTrail'},
        {name: 'instShoot', cn: 'instShoot'},
        {name: 'instHit', cn: 'instHit'},
        {name: 'hitLaser', cn: 'hitLaser'},
        {name: 'hitLaserColor', cn: 'hitLaserColor'},
        {name: 'despawn', cn: 'despawn'},
        {name: 'airBubble', cn: 'airBubble'},
        {name: 'flakExplosion', cn: 'flakExplosion'},
        {name: 'plasticExplosion', cn: 'plasticExplosion'},
        {name: 'plasticExplosionFlak', cn: 'plasticExplosionFlak'},
        {name: 'blastExplosion', cn: 'blastExplosion'},
        {name: 'sapExplosion', cn: 'sapExplosion'},
        {name: 'massiveExplosion', cn: 'massiveExplosion'},
        {name: 'artilleryTrail', cn: 'artilleryTrail'},
        {name: 'incendTrail', cn: 'incendTrail'},
        {name: 'missileTrail', cn: 'missileTrail'},
        {name: 'missileTrailShort', cn: 'missileTrailShort'},
        {name: 'bulletSparkSmokeTrailSmall', cn: 'bulletSparkSmokeTrailSmall'},
        {name: 'colorTrail', cn: 'colorTrail'},
        {name: 'absorb', cn: 'absorb'},
        {name: 'forceShrink', cn: 'forceShrink'},
        {name: 'flakExplosionBig', cn: 'flakExplosionBig'},
        {name: 'burning', cn: 'burning'},
        {name: 'fireRemove', cn: 'fireRemove'},
        {name: 'fire', cn: 'fire'},
        {name: 'fireHit', cn: 'fireHit'},
        {name: 'fireSmoke', cn: 'fireSmoke'},
        {name: 'neoplasmHeal', cn: 'neoplasmHeal'},
        {name: 'steam', cn: 'steam'},
        {name: 'ventSteam', cn: 'ventSteam'},
        {name: 'drillSteam', cn: 'drillSteam'},
        {name: 'fluxVapor', cn: 'fluxVapor'},
        {name: 'corrosionVapor', cn: 'corrosionVapor'},
        {name: 'vapor', cn: 'vapor'},
        {name: 'vaporSmall', cn: 'vaporSmall'},
        {name: 'fireballsmoke', cn: 'fireballsmoke'},
        {name: 'ballfire', cn: 'ballfire'},
        {name: 'freezing', cn: 'freezing'},
        {name: 'melting', cn: 'melting'},
        {name: 'wet', cn: 'wet'},
        {name: 'muddy', cn: 'muddy'},
        {name: 'sapped', cn: 'sapped'},
        {name: 'electrified', cn: 'electrified'},
        {name: 'sporeSlowed', cn: 'sporeSlowed'},
        {name: 'oily', cn: 'oily'},
        {name: 'overdriven', cn: 'overdriven'},
        {name: 'overclocked', cn: 'overclocked'},
        {name: 'dropItem', cn: 'dropItem'},
        {name: 'shockwave', cn: 'shockwave'},
        {name: 'shockwaveSmaller', cn: 'shockwaveSmaller'},
        {name: 'bigShockwave', cn: 'bigShockwave'},
        {name: 'spawnShockwave', cn: 'spawnShockwave'},
        {name: 'podLandShockwave', cn: 'podLandShockwave'},
        {name: 'explosion', cn: 'explosion'},
        {name: 'dynamicExplosion', cn: 'dynamicExplosion'},
        {name: 'reactorExplosion', cn: 'reactorExplosion'},
        {name: 'impactReactorExplosion', cn: 'impactReactorExplosion'},
        {name: 'blockExplosionSmoke', cn: 'blockExplosionSmoke'},
        {name: 'steamCoolSmoke', cn: 'steamCoolSmoke'},
        {name: 'smokePuff', cn: 'smokePuff'},
        {name: 'shootSmall', cn: 'shootSmall'},
        {name: 'shootSmallColor', cn: 'shootSmallColor'},
        {name: 'shootHeal', cn: 'shootHeal'},
        {name: 'shootHealYellow', cn: 'shootHealYellow'},
        {name: 'shootSmallSmoke', cn: 'shootSmallSmoke'},
        {name: 'shootBig', cn: 'shootBig'},
        {name: 'shootBig2', cn: 'shootBig2'},
        {name: 'shootBigColor', cn: 'shootBigColor'},
        {name: 'shootScepterSecondary', cn: 'shootScepterSecondary'},
        {name: 'shootQuellPulse', cn: 'shootQuellPulse'},
        {name: 'shootTitan', cn: 'shootTitan'},
        {name: 'shootBigSmoke', cn: 'shootBigSmoke'},
        {name: 'shootBigSmoke2', cn: 'shootBigSmoke2'},
        {name: 'shootSmokeDisperse', cn: 'shootSmokeDisperse'},
        {name: 'shootSmokeSquare', cn: 'shootSmokeSquare'},
        {name: 'shootSmokeSquareSparse', cn: 'shootSmokeSquareSparse'},
        {name: 'shootSmokeSquareBig', cn: 'shootSmokeSquareBig'},
        {name: 'shootSmokeTitan', cn: 'shootSmokeTitan'},
        {name: 'shootSmokeSmite', cn: 'shootSmokeSmite'},
        {name: 'shootSmokeMissile', cn: 'shootSmokeMissile'},
        {name: 'shootSmokeMissileColor', cn: 'shootSmokeMissileColor'},
        {name: 'regenParticle', cn: 'regenParticle'},
        {name: 'regenSuppressParticle', cn: 'regenSuppressParticle'},
        {name: 'regenSuppressSeek', cn: 'regenSuppressSeek'},
        {name: 'surgeCruciSmoke', cn: 'surgeCruciSmoke'},
        {name: 'neoplasiaSmoke', cn: 'neoplasiaSmoke'},
        {name: 'heatReactorSmoke', cn: 'heatReactorSmoke'},
        {name: 'circleColorSpark', cn: 'circleColorSpark'},
        {name: 'colorSpark', cn: 'colorSpark'},
        {name: 'colorSparkBig', cn: 'colorSparkBig'},
        {name: 'randLifeSpark', cn: 'randLifeSpark'},
        {name: 'shootPayloadDriver', cn: 'shootPayloadDriver'},
        {name: 'shootSmallFlame', cn: 'shootSmallFlame'},
        {name: 'shootPyraFlame', cn: 'shootPyraFlame'},
        {name: 'shootLiquid', cn: 'shootLiquid'},
        {name: 'casing1', cn: 'casing1'},
        {name: 'casing2', cn: 'casing2'},
        {name: 'casing3', cn: 'casing3'},
        {name: 'casing4', cn: 'casing4'},
        {name: 'casing2Double', cn: 'casing2Double'},
        {name: 'casing3Double', cn: 'casing3Double'},
        {name: 'railShoot', cn: 'railShoot'},
        {name: 'railTrail', cn: 'railTrail'},
        {name: 'railHit', cn: 'railHit'},
        {name: 'lancerLaserShoot', cn: 'lancerLaserShoot'},
        {name: 'lancerLaserShootSmoke', cn: 'lancerLaserShootSmoke'},
        {name: 'lancerLaserCharge', cn: 'lancerLaserCharge'},
        {name: 'lancerLaserChargeBegin', cn: 'lancerLaserChargeBegin'},
        {name: 'lightningCharge', cn: 'lightningCharge'},
        {name: 'sparkShoot', cn: 'sparkShoot'},
        {name: 'lightningShoot', cn: 'lightningShoot'},
        {name: 'thoriumShoot', cn: 'thoriumShoot'},
        {name: 'reactorsmoke', cn: 'reactorsmoke'},
        {name: 'redgeneratespark', cn: 'redgeneratespark'},
        {name: 'turbinegenerate', cn: 'turbinegenerate'},
        {name: 'generatespark', cn: 'generatespark'},
        {name: 'fuelburn', cn: 'fuelburn'},
        {name: 'incinerateSlag', cn: 'incinerateSlag'},
        {name: 'coreBurn', cn: 'coreBurn'},
        {name: 'plasticburn', cn: 'plasticburn'},
        {name: 'conveyorPoof', cn: 'conveyorPoof'},
        {name: 'pulverize', cn: 'pulverize'},
        {name: 'pulverizeRed', cn: 'pulverizeRed'},
        {name: 'pulverizeSmall', cn: 'pulverizeSmall'},
        {name: 'pulverizeMedium', cn: 'pulverizeMedium'},
        {name: 'producesmoke', cn: 'producesmoke'},
        {name: 'artilleryTrailSmoke', cn: 'artilleryTrailSmoke'},
        {name: 'smokeCloud', cn: 'smokeCloud'},
        {name: 'smeltsmoke', cn: 'smeltsmoke'},
        {name: 'coalSmeltsmoke', cn: 'coalSmeltsmoke'},
        {name: 'formsmoke', cn: 'formsmoke'},
        {name: 'blastsmoke', cn: 'blastsmoke'},
        {name: 'lava', cn: 'lava'},
        {name: 'dooropen', cn: 'dooropen'},
        {name: 'doorclose', cn: 'doorclose'},
        {name: 'dooropenlarge', cn: 'dooropenlarge'},
        {name: 'doorcloselarge', cn: 'doorcloselarge'},
        {name: 'generate', cn: 'generate'},
        {name: 'mineWallSmall', cn: 'mineWallSmall'},
        {name: 'mineSmall', cn: 'mineSmall'},
        {name: 'mine', cn: 'mine'},
        {name: 'mineBig', cn: 'mineBig'},
        {name: 'mineHuge', cn: 'mineHuge'},
        {name: 'mineImpact', cn: 'mineImpact'},
        {name: 'mineImpactWave', cn: 'mineImpactWave'},
        {name: 'payloadReceive', cn: 'payloadReceive'},
        {name: 'teleportActivate', cn: 'teleportActivate'},
        {name: 'teleport', cn: 'teleport'},
        {name: 'teleportOut', cn: 'teleportOut'},
        {name: 'ripple', cn: 'ripple'},
        {name: 'bubble', cn: 'bubble'},
        {name: 'launchAccelerator', cn: 'launchAccelerator'},
        {name: 'launch', cn: 'launch'},
        {name: 'launchPod', cn: 'launchPod'},
        {name: 'healWaveMend', cn: 'healWaveMend'},
        {name: 'overdriveWave', cn: 'overdriveWave'},
        {name: 'healBlock', cn: 'healBlock'},
        {name: 'healBlockFull', cn: 'healBlockFull'},
        {name: 'rotateBlock', cn: 'rotateBlock'},
        {name: 'lightBlock', cn: 'lightBlock'},
        {name: 'overdriveBlockFull', cn: 'overdriveBlockFull'},
        {name: 'shieldBreak', cn: 'shieldBreak'},
        {name: 'arcShieldBreak', cn: 'arcShieldBreak'},
        {name: 'coreLandDust', cn: 'coreLandDust'},
        {name: 'podLandDust', cn: 'podLandDust'},
        {name: 'unitShieldBreak', cn: 'unitShieldBreak'},
        {name: 'chainLightning', cn: 'chainLightning'},
        {name: 'chainEmp', cn: 'chainEmp'},
        {name: 'legDestroy', cn: 'legDestroy'},
        {name: 'debugLine', cn: 'debugLine'},
        {name: 'debugRect', cn: 'debugRect'},
    ],
};
