name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
        working-directory: packages/backend
      - run: npm run build
        working-directory: packages/backend

      - name: Create archives
        run: |
          tar -czf backend-dist.tar.gz -C packages/backend/dist .

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            backend-dist.tar.gz